export interface IPaciente {
    "idClinica": number,
    "idPaciente": number,
    "nombre": string,
    "movilDeEnvio": string,
    "telefonoParaMostrar": string,
    "MedioDeComunicacion": number,
    "Sexo": string,
    "activo": number,
    "correoDeEnvio": string,
    "direccionParaMostrar": string,
    "fechaCumpleaños": string,
    "fechaNacimiento": string,
    "idDoctor": number,
    "idEstado": number,
    "idEstadoPersonalizado": number,
    "idParaElDentista": string,
    "nota": string,
    "tieneAlertaPorCuestionario": number,
    "versionFotoPerfil": number,
}